### PR TITLE
Update yarn.lock

### PR DESCRIPTION
**Pull request by serv**
When I ran `$ yarn`, there were some changes to `yarn.lock`.

### CODE REVIEW

**Comment by nmaro** [comment]
Strange... Shouldn't yarn.lock be fixed unless you install something new?

**Comment by serv** [comment]
I think that's the idea behind the yarn.lock.

This is the log when I run `yarn`.

```
$ yarn 
yarn install v0.23.3
[1/4] Resolving packages...
warning Integrity check: Patterns don't match
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 44.16s.

```

**Comment by serv** [comment]
It's cool if you don't feel the need to merge this.

**Comment by nmaro** [comment]
Ok I'll close it since meanwhile it has changed anyway ;)

**Pull request closed without merging**
